<?php
if (!defined('ABSPATH')) { exit; }
class ALMA_AI_Usage_Logger {
    public static function table_name(){ global $wpdb; return $wpdb->prefix.'alma_ai_usage'; }
    public static function create_table(){ global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $t=self::table_name(); $c=$wpdb->get_charset_collate(); dbDelta("CREATE TABLE IF NOT EXISTS $t (id bigint unsigned NOT NULL AUTO_INCREMENT,created_at datetime NOT NULL,provider varchar(20) NOT NULL,model varchar(100) NOT NULL,task varchar(100) DEFAULT '' NOT NULL,input_tokens bigint NULL,output_tokens bigint NULL,estimated_cost decimal(12,6) NULL,response_time int NULL,success tinyint(1) NOT NULL DEFAULT 0,error_message text NULL,reference_id varchar(100) DEFAULT '' NOT NULL,PRIMARY KEY(id),KEY created_at(created_at)) $c;"); }
    public static function log($d){ global $wpdb; $wpdb->insert(self::table_name(), array('created_at'=>current_time('mysql'),'provider'=>'openai','model'=>sanitize_text_field($d['model']??''),'task'=>sanitize_text_field($d['task']??''),'input_tokens'=>isset($d['input_tokens'])?(int)$d['input_tokens']:null,'output_tokens'=>isset($d['output_tokens'])?(int)$d['output_tokens']:null,'estimated_cost'=>isset($d['estimated_cost'])?(float)$d['estimated_cost']:null,'response_time'=>isset($d['response_time'])?(int)$d['response_time']:null,'success'=>!empty($d['success'])?1:0,'error_message'=>isset($d['error'])?sanitize_text_field($d['error']):null,'reference_id'=>sanitize_text_field($d['reference_id']??'')), array('%s','%s','%s','%s','%d','%d','%f','%d','%d','%s','%s')); }
    public static function get_recent_logs($limit=20){ global $wpdb; return $wpdb->get_results($wpdb->prepare("SELECT * FROM ".self::table_name()." ORDER BY created_at DESC LIMIT %d", absint($limit)), ARRAY_A); }
    public static function get_total_estimated_cost(){ global $wpdb; return (float)$wpdb->get_var("SELECT COALESCE(SUM(estimated_cost),0) FROM ".self::table_name()); }
}
