<?php
if (!defined('ABSPATH')) { exit; }

class ALMA_Affiliate_Source_Viator_Field_Catalog {
    public static function get_catalog() {
        return array(
            self::row('products[].productCode','Product code','Identità prodotto','/products/search, /search/freetext','string','Codice prodotto Viator.','ABC123','external_id','documented',''),
            self::row('products[].title','Titolo','Identità prodotto','/products/search, /search/freetext','string','Titolo esperienza.','Tour guidato','titolo','documented',''),
            self::row('products[].description','Descrizione','Identità prodotto','/products/search, /search/freetext','string','Descrizione breve prodotto.','Esperienza con guida...','descrizione','documented',''),
            self::row('products[].productUrl','Product URL','Identità prodotto','/products/search, /search/freetext','string','URL affiliato Viator da salvare completo senza modifiche.','https://www.viator.com/...','URL affiliato','affiliate_ready','Salvare completo senza modifiche tracking.'),
            self::row('products[].confirmationType','Tipo conferma','Identità prodotto','/products/search','string','Modalità conferma prenotazione (istantanea/su richiesta).','INSTANT','stato prenotazione','advanced',''),
            self::row('products[].itineraryType','Tipo itinerario','Identità prodotto','/products/search','string','Formato itinerario del prodotto.','MULTI_DAY','categoria tecnica','advanced',''),
            self::row('products[].images[]','Immagini','Immagini','/products/search','array','Elenco immagini associate al prodotto.','[ ... ]','galleria','documented',''),
            self::row('products[].images[].imageSource','Sorgente immagine','Immagini','/products/search','string','Origine immagine nel catalogo Viator.','SUPPLIER','metadata media','advanced',''),
            self::row('products[].images[].caption','Caption immagine','Immagini','/products/search','string','Didascalia immagine.','Vista panoramica','caption','documented',''),
            self::row('products[].images[].isCover','Immagine cover','Immagini','/products/search','boolean','Indica se l\'immagine è cover principale.','true','immagine evidenza','documented',''),
            self::row('products[].images[].variants[]','Varianti immagine','Immagini','/products/search','array','Varianti immagine per dimensioni/formato.','[ ... ]','responsive images','advanced',''),
            self::row('products[].images[].variants[].url','URL variante immagine','Immagini','/products/search','string','URL della variante immagine.','https://...jpg','thumbnail/hero','affiliate_ready',''),
            self::row('products[].images[].variants[].width','Larghezza variante','Immagini','/products/search','integer','Larghezza immagine in pixel.','800','dimensione media','documented',''),
            self::row('products[].images[].variants[].height','Altezza variante','Immagini','/products/search','integer','Altezza immagine in pixel.','600','dimensione media','documented',''),
            self::row('products[].videos[]','Video','Video','/products/search','array','Video disponibili per il prodotto.','[ ... ]','media avanzati','advanced',''),
            self::row('products[].videos[].language','Lingua video','Video','/products/search','string','Lingua associata al video.','en','lingua contenuto','advanced',''),
            self::row('products[].videos[].variants.streaming[]','Varianti streaming','Video','/products/search','array','URL varianti streaming video.','[ ... ]','player streaming','advanced',''),
            self::row('products[].videos[].variants.progressive[]','Varianti progressive','Video','/products/search','array','URL varianti download/progressive.','[ ... ]','player download','advanced',''),
            self::row('products[].pricing.summary.fromPrice','Prezzo da','Prezzi','/products/search, /search/freetext','number','Prezzo minimo visibile al cliente.','49.99','prezzo','documented',''),
            self::row('products[].pricing.summary.fromPriceBeforeDiscount','Prezzo pre-sconto','Prezzi','/products/search','number','Prezzo prima di eventuali sconti.','59.99','prezzo barrato','advanced',''),
            self::row('products[].pricing.currency','Valuta','Prezzi','/products/search','string','Valuta ISO del prezzo.','EUR','valuta','documented',''),
            self::row('products[].pricing.partnerNetFromPrice','Prezzo partner netto','Prezzi','/products/search','number','Prezzo netto partner (se disponibile).','41.50','marginalità interna','advanced',''),
            self::row('products[].pricing.extraChargesSummary.fromPrice','Prezzo con extra','Prezzi','/products/search','number','Prezzo di partenza considerando extra.','52.00','prezzo totale iniziale','advanced',''),
            self::row('products[].pricing.extraChargesSummary.extraCharges','Dettaglio extra','Prezzi','/products/search','array','Lista sovrapprezzi applicabili.','[ ... ]','dettaglio costo','advanced',''),
            self::row('products[].reviews.totalReviews','Numero recensioni','Recensioni aggregate','/products/search','integer','Numero recensioni aggregate disponibili.','1240','social proof','documented',''),
            self::row('products[].reviews.combinedAverageRating','Voto medio aggregato','Recensioni aggregate','/products/search','number','Valutazione media aggregata.','4.6','rating','documented',''),
            self::row('products[].reviews.sources[]','Fonti recensioni','Recensioni aggregate','/products/search','array','Elenco provider usati per aggregazione.','[ ... ]','diagnostica fonti','advanced',''),
            self::row('products[].reviews.sources[].provider','Provider recensioni','Recensioni aggregate','/products/search','string','Nome provider origine recensioni.','VIATOR','fonte recensioni','advanced',''),
            self::row('products[].reviews.sources[].totalCount','Totale recensioni fonte','Recensioni aggregate','/products/search','integer','Numero recensioni per provider.','980','diagnostica','advanced',''),
            self::row('products[].reviews.sources[].averageRating','Media recensioni fonte','Recensioni aggregate','/products/search','number','Voto medio per provider.','4.7','diagnostica','advanced',''),
            self::row('products[].duration.fixedDurationInMinutes','Durata fissa minuti','Durata','/products/search','integer','Durata fissa del prodotto in minuti.','180','durata','documented',''),
            self::row('products[].duration.variableDurationFromMinutes','Durata minima minuti','Durata','/products/search','integer','Durata variabile minima in minuti.','90','durata minima','documented',''),
            self::row('products[].duration.variableDurationToMinutes','Durata massima minuti','Durata','/products/search','integer','Durata variabile massima in minuti.','240','durata massima','documented',''),
            self::row('products[].duration.unstructuredDuration','Durata testuale','Durata','/products/search','string','Durata in formato testuale.','Circa mezza giornata','durata descrittiva','advanced',''),
            self::row('products[].destinations[]','Destinazioni','Destinazioni e categorie','/products/search','array','Destinazioni associate al prodotto.','[ ... ]','taxonomy esterna','documented',''),
            self::row('products[].destinations[].ref','Ref destinazione','Destinazioni e categorie','/products/search','string','ID destinazione Viator. Da risolvere con /destinations.','684','destination_id','documented',''),
            self::row('products[].destinations[].primary','Destinazione primaria','Destinazioni e categorie','/products/search','boolean','Segna la destinazione principale.','true','destinazione principale','documented',''),
            self::row('products[].tags[]','Tag prodotto','Destinazioni e categorie','/products/search','array','ID tag/categoria Viator. Da risolvere con /products/tags.','[21972,30295]','tag esterni','documented',''),
            self::row('products[].flags[]','Flag prodotto','Destinazioni e categorie','/products/search','array','Flag funzionali/commerciali Viator.','[ ... ]','filtri avanzati','advanced',''),
            self::row('products[].translationInfo.containsMachineTranslatedText','Traduzione automatica','Traduzioni','/products/search','boolean','Indica presenza testo tradotto automaticamente.','false','quality check','advanced',''),
            self::row('products[].translationInfo.translationSource','Fonte traduzione','Traduzioni','/products/search','string','Origine traduzione testo.','HUMAN','audit contenuto','advanced',''),
            self::row('status','Status dettaglio','Dettaglio prodotto','/products/{product-code}','string','Stato del record prodotto dettaglio.','ACTIVE','stato tecnico','documented',''),
            self::row('language','Lingua dettaglio','Dettaglio prodotto','/products/{product-code}','string','Lingua del payload dettaglio.','it','locale contenuto','documented',''),
            self::row('createdAt','Data creazione','Dettaglio prodotto','/products/{product-code}','datetime','Data creazione record Viator.','2025-04-12T10:00:00Z','audit','advanced',''),
            self::row('lastUpdatedAt','Data aggiornamento','Dettaglio prodotto','/products/{product-code}','datetime','Data ultimo aggiornamento record.','2026-01-20T08:30:00Z','audit','advanced',''),
            self::row('ticketInfo.ticketTypes[]','Tipi ticket','Dettaglio prodotto','/products/{product-code}','array','Tipologie ticket supportate.','[ ... ]','logica pricing','advanced',''),
            self::row('ticketInfo.ticketTypeDescription','Descrizione ticket','Dettaglio prodotto','/products/{product-code}','string','Descrizione tipologia ticket.','Mobile ticket','UX checkout','advanced',''),
            self::row('pricingInfo.type','Tipo pricing','Dettaglio prodotto','/products/{product-code}','string','Tipo struttura prezzi del prodotto.','PER_PERSON','pricing model','advanced',''),
            self::row('pricingInfo.ageBands[]','Fasce età','Dettaglio prodotto','/products/{product-code}','array','Fasce età disponibili per pricing.','[ ... ]','pricing dettaglio','advanced',''),
            self::row('pricingInfo.ageBands[].ageBand','Nome fascia età','Dettaglio prodotto','/products/{product-code}','string','Nome fascia età.','ADULT','fascia prezzo','advanced',''),
            self::row('pricingInfo.ageBands[].startAge','Età inizio','Dettaglio prodotto','/products/{product-code}','integer','Età minima inclusa nella fascia.','18','regole prezzo','advanced',''),
            self::row('pricingInfo.ageBands[].endAge','Età fine','Dettaglio prodotto','/products/{product-code}','integer','Età massima inclusa nella fascia.','64','regole prezzo','advanced',''),
            self::row('pricingInfo.ageBands[].minTravelersPerBooking','Min pax booking fascia','Dettaglio prodotto','/products/{product-code}','integer','Minimo viaggiatori per fascia.','1','vincoli booking','advanced',''),
            self::row('pricingInfo.ageBands[].maxTravelersPerBooking','Max pax booking fascia','Dettaglio prodotto','/products/{product-code}','integer','Massimo viaggiatori per fascia.','15','vincoli booking','advanced',''),
            self::row('logistics.start[]','Logistica start','Dettaglio prodotto','/products/{product-code}','array','Informazioni punto/ora partenza.','[ ... ]','itinerario','advanced',''),
            self::row('logistics.end[]','Logistica end','Dettaglio prodotto','/products/{product-code}','array','Informazioni punto/ora arrivo.','[ ... ]','itinerario','advanced',''),
            self::row('logistics.travelerPickup','Pickup viaggiatore','Dettaglio prodotto','/products/{product-code}','boolean','Indica se è previsto pickup del viaggiatore.','true','servizi inclusi','advanced',''),
            self::row('timeZone','Fuso orario','Dettaglio prodotto','/products/{product-code}','string','Fuso orario operativo del prodotto.','Europe/Rome','orari','advanced',''),
            self::row('inclusions[]','Inclusioni','Dettaglio prodotto','/products/{product-code}','array','Servizi inclusi nel prezzo.','[ ... ]','dettagli offerta','documented',''),
            self::row('exclusions[]','Esclusioni','Dettaglio prodotto','/products/{product-code}','array','Servizi esclusi dal prezzo.','[ ... ]','dettagli offerta','documented',''),
            self::row('additionalInfo[]','Info aggiuntive','Dettaglio prodotto','/products/{product-code}','array','Informazioni operative aggiuntive.','[ ... ]','note prodotto','advanced',''),
            self::row('cancellationPolicy.type','Tipo policy cancellazione','Dettaglio prodotto','/products/{product-code}','string','Tipo policy cancellazione prevista.','STANDARD','policy cancellazione','advanced',''),
            self::row('cancellationPolicy.description','Descrizione policy cancellazione','Dettaglio prodotto','/products/{product-code}','string','Descrizione policy cancellazione.','Cancellazione gratuita...','testo policy','advanced',''),
            self::row('cancellationPolicy.refundEligibility[]','Regole rimborso','Dettaglio prodotto','/products/{product-code}','array','Regole eleggibilità rimborso.','[ ... ]','refund rules','advanced',''),
            self::row('bookingRequirements.minTravelersPerBooking','Min pax booking','Dettaglio prodotto','/products/{product-code}','integer','Minimo partecipanti per prenotazione.','1','vincoli prenotazione','advanced',''),
            self::row('bookingRequirements.maxTravelersPerBooking','Max pax booking','Dettaglio prodotto','/products/{product-code}','integer','Massimo partecipanti per prenotazione.','12','vincoli prenotazione','advanced',''),
            self::row('bookingRequirements.requiresAdultForBooking','Adulto obbligatorio','Dettaglio prodotto','/products/{product-code}','boolean','Richiede almeno un adulto in prenotazione.','true','vincoli prenotazione','advanced',''),
            self::row('languageGuides[]','Guide lingua','Dettaglio prodotto','/products/{product-code}','array','Lingue guide disponibili.','[ ... ]','filtri lingua','advanced',''),
            self::row('bookingQuestions[]','Domande booking','Dettaglio prodotto','/products/{product-code}','array','Domande richieste in fase prenotazione.','[ ... ]','form prenotazione','advanced',''),
            self::row('productOptions[]','Opzioni prodotto','Dettaglio prodotto','/products/{product-code}','array','Opzioni acquistabili del prodotto.','[ ... ]','varianti prodotto','advanced',''),
            self::row('productOptions[].productOptionCode','Codice opzione','Dettaglio prodotto','/products/{product-code}','string','Codice opzione prodotto.','P123-OPT1','option id','advanced',''),
            self::row('productOptions[].title','Titolo opzione','Dettaglio prodotto','/products/{product-code}','string','Titolo opzione prodotto.','Tour mattina','titolo opzione','advanced',''),
            self::row('productOptions[].description','Descrizione opzione','Dettaglio prodotto','/products/{product-code}','string','Descrizione opzione prodotto.','Partenza ore 09:00','descrizione opzione','advanced',''),
            self::row('supplier.name','Nome supplier','Dettaglio prodotto','/products/{product-code}','string','Nome fornitore operativo.','Best Tours SRL','supplier','advanced',''),
            self::row('supplier.reference','Reference supplier','Dettaglio prodotto','/products/{product-code}','string','Riferimento supplier Viator.','SUP-7788','supplier_id','advanced',''),
            self::row('viatorUniqueContent','Contenuto unico Viator','Dettaglio prodotto','/products/{product-code}','string','Contenuto soggetto a regole compliance Viator.','...','contenuto protetto','protected','Uso soggetto a policy contenuti Viator.'),
            self::row('/destinations: destinations[].destinationId','Destination ID','Reference data','/destinations','integer','ID destinazione Viator usato nella ricerca prodotti.','684','default_destination_id','documented',''),
            self::row('/destinations: destinations[].name','Nome destinazione','Reference data','/destinations','string','Nome destinazione Viator.','Rome','lookup destinazione','documented',''),
            self::row('/destinations: destinations[].type','Tipo destinazione','Reference data','/destinations','string','Tipo nodo destinazione.','CITY','lookup destinazione','advanced',''),
            self::row('/destinations: destinations[].parentDestinationId','Parent destination ID','Reference data','/destinations','integer','ID destinazione padre.','45','albero destinazioni','advanced',''),
            self::row('/products/tags: tags[].tagId','Tag ID','Reference data','/products/tags','integer','ID tag/categoria Viator.','21972','tag_id','documented',''),
            self::row('/products/tags: tags[].name','Nome tag','Reference data','/products/tags','string','Nome tag/categoria Viator.','Tour culturali','lookup tag','documented',''),
            self::row('/products/tags: tags[].parentTagId','Parent tag ID','Reference data','/products/tags','integer','ID tag padre.','20000','albero tag','advanced',''),
            self::row('/locations/bulk: locations[].reference','Reference location','Reference data','/locations/bulk','string','Reference location Viator.','LOC-001','location_ref','advanced',''),
            self::row('/locations/bulk: locations[].name','Nome location','Reference data','/locations/bulk','string','Nome location.','Piazza Navona','lookup location','advanced',''),
            self::row('/locations/bulk: locations[].address','Indirizzo location','Reference data','/locations/bulk','string','Indirizzo completo location.','Piazza Navona, Roma','indirizzo','advanced',''),
            self::row('/locations/bulk: locations[].center.latitude','Latitudine location','Reference data','/locations/bulk','number','Coordinata latitudine.','41.8992','geo_lat','advanced',''),
            self::row('/locations/bulk: locations[].center.longitude','Longitudine location','Reference data','/locations/bulk','number','Coordinata longitudine.','12.4731','geo_lng','advanced',''),
            self::row('/availability/check','Availability check','Booking transazionale','/availability/check','object','Endpoint disponibilità per booking transazionale.','POST payload','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/hold','Hold booking','Booking transazionale','/bookings/hold','object','Hold prenotazione transazionale.','POST payload','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/cart/hold','Hold booking carrello','Booking transazionale','/bookings/cart/hold','object','Hold carrello prenotazione transazionale.','POST payload','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/book','Book booking','Booking transazionale','/bookings/book','object','Conferma prenotazione transazionale.','POST payload','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/cart/book','Book carrello','Booking transazionale','/bookings/cart/book','object','Conferma prenotazione da carrello.','POST payload','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/status','Status booking','Booking transazionale','/bookings/status','object','Stato prenotazione transazionale.','GET response','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/cancel-reasons','Motivi cancellazione','Booking transazionale','/bookings/cancel-reasons','object','Motivi cancellazione booking.','GET response','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/{booking-reference}/cancel-quote','Preventivo cancellazione','Booking transazionale','/bookings/{booking-reference}/cancel-quote','object','Calcolo penale cancellazione booking.','GET response','n/d','transactional_not_implemented','Transazionale / non implementato.'),
            self::row('/bookings/{booking-reference}/cancel','Cancellazione booking','Booking transazionale','/bookings/{booking-reference}/cancel','object','Esecuzione cancellazione booking.','POST payload','n/d','transactional_not_implemented','Transazionale / non implementato.'),
        );
    }

    private static function row($path,$label,$group,$endpoint,$type,$description,$example,$mapping_hint,$status,$compliance_note='') {
        return array('path'=>(string)$path,'label'=>(string)$label,'group'=>(string)$group,'endpoint'=>(string)$endpoint,'type'=>(string)$type,'description'=>(string)$description,'example'=>(string)$example,'mapping_hint'=>(string)$mapping_hint,'status'=>(string)$status,'compliance_note'=>(string)$compliance_note);
    }
}
