<?php
if (!defined('ABSPATH')) { exit; }

class ALMA_Affiliate_Source_Provider_Presets {
    public static function get_schema() {
        return array(
            'manual' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'manual','unsupported_message'=>'Provider non ancora supportato per test/discovery.','label'=>'Manual','provider_key'=>'manual','description'=>'Gestione manuale senza API.','modes'=>array('manual'),'settings_fields'=>array(),'credentials_fields'=>array(),'required_fields'=>array(),'optional_fields'=>array(),'help_text'=>'Usa questa modalità per inserimenti manuali.','commercial_notes'=>''),
            'custom_api' => array('supports_connection_test'=>true,'supports_field_discovery'=>true,'provider_type'=>'api','unsupported_message'=>'','label'=>'Custom API','provider_key'=>'custom_api','description'=>'Provider API personalizzato.','modes'=>array('api','deeplink','widget','xml_api','manual'),'settings_fields'=>self::common_settings(),'credentials_fields'=>self::common_credentials(),'required_fields'=>array(),'optional_fields'=>array(),'help_text'=>'Configura endpoint e credenziali del provider custom.','commercial_notes'=>''),
            'viator' => array('supports_connection_test'=>true,'supports_field_discovery'=>true,'provider_type'=>'commercial_api','unsupported_message'=>'','label'=>'Viator','provider_key'=>'viator','description'=>'Viator Partner API v2 (solo flusso affiliate base).','modes'=>array('api','deeplink'),'settings_fields'=>self::viator_settings(),'credentials_fields'=>self::viator_credentials(),'required_fields'=>array('environment','accept_language','api_version','search_model','api_key'),'optional_fields'=>array('currency','default_destination_id','default_search_term','result_count','sort','sort_order','campaign_value','target_lander','partner_access_level'),'help_text'=>'La API key è una credenziale segreta: inviata solo come header exp-api-key e mai esposta in HTML/JS/URL/log.','commercial_notes'=>'Basic Affiliate supportato; booking/checkout/pagamenti esclusi in questa release.'),
            'getyourguide' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'GetYourGuide','provider_key'=>'getyourguide','description'=>'Marketplace Partner API o Connectivity.','modes'=>array('api','deeplink','widget'),'settings_fields'=>array('integration_type','base_url','currency','cnt_language','locale','mode'),'credentials_fields'=>array('access_token','username','password'),'required_fields'=>array('integration_type'),'optional_fields'=>array('access_token','username','password'),'help_text'=>'Partner API usa X-ACCESS-TOKEN; Connectivity usa Basic Auth.','commercial_notes'=>'Accesso dipende dall’approvazione partnership.'),
            'tiqets' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'Tiqets','provider_key'=>'tiqets','description'=>'Distributor API Tiqets.','modes'=>array('api','deeplink','widget'),'settings_fields'=>array('environment','base_url','user_agent','sitebrand','mode','api_version'),'credentials_fields'=>array('api_key','jwt_signing_key','jwt_key_id'),'required_fields'=>array('base_url','user_agent','api_key'),'optional_fields'=>array('jwt_signing_key','jwt_key_id'),'help_text'=>'Authorization: Token; User-Agent richiesto.','commercial_notes'=>''),
            'booking_com' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'Booking.com','provider_key'=>'booking_com','description'=>'Demand API e deeplink.','modes'=>array('demand_api','deeplink'),'settings_fields'=>array('environment','api_version','base_url','currency','language','booker_country','platform','mode'),'credentials_fields'=>array('api_key','affiliate_id'),'required_fields'=>array('mode'),'optional_fields'=>array('api_key','affiliate_id'),'help_text'=>'Bearer API key e X-Affiliate-Id per Demand API.','commercial_notes'=>'Può richiedere approvazione account partner.'),
            'agoda' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'Agoda','provider_key'=>'agoda','description'=>'Search/Book/Content API Agoda.','modes'=>array('search_api','book_api','content_api'),'settings_fields'=>array('environment','partnership_model','language','currency','user_country','mode','rates_per_property','extra_features'),'credentials_fields'=>array('site_id','api_key'),'required_fields'=>array('mode'),'optional_fields'=>array('site_id','api_key'),'help_text'=>'Header Authorization: siteId:apikey per Search API.','commercial_notes'=>'Credenziali dopo processo commerciale/certificazione.'),
            'aviasales' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'Aviasales / Travelpayouts','provider_key'=>'aviasales','description'=>'Data API e Flight Search API.','modes'=>array('api','deeplink'),'settings_fields'=>array('integration_type','market','locale','currency','real_host','mode','default_origin','default_destination'),'credentials_fields'=>array('api_token','marker'),'required_fields'=>array('integration_type'),'optional_fields'=>array('real_host','marker'),'help_text'=>'Predisposti campi per signature Flight Search senza implementarla ora.','commercial_notes'=>''),
            'discovercars' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'DiscoverCars','provider_key'=>'discovercars','description'=>'Deeplink/widget/XML API.','modes'=>array('deeplink','widget','xml_api'),'settings_fields'=>array('mode','network','tracking_subid','widget_enabled','xml_environment'),'credentials_fields'=>array('affiliate_id','tracking_code','xml_api_key','xml_username','xml_password'),'required_fields'=>array('mode'),'optional_fields'=>array('xml_api_key','xml_username','xml_password'),'help_text'=>'Per deeplink/widget API key XML non obbligatoria.','commercial_notes'=>'XML API disponibile solo per partner abilitati.'),
            'airalo' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'Airalo','provider_key'=>'airalo','description'=>'Partner API o deeplink.','modes'=>array('partner_api','deeplink'),'settings_fields'=>array('environment','base_url','currency','locale','brand','mode'),'credentials_fields'=>array('client_id','client_secret'),'required_fields'=>array('mode'),'optional_fields'=>array('client_id','client_secret'),'help_text'=>'Client credentials per token OAuth.','commercial_notes'=>''),
            'omio' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'Omio','provider_key'=>'omio','description'=>'Search API, widget, deeplink.','modes'=>array('search_api','widget','deeplink'),'settings_fields'=>array('mode','market','language','currency','default_transport_modes','tracking_subid'),'credentials_fields'=>array('affiliate_id','api_key'),'required_fields'=>array('mode'),'optional_fields'=>array('api_key'),'help_text'=>'api_key opzionale in deeplink/widget.','commercial_notes'=>'Dettagli API dopo approvazione partnership.'),
            'safetywing' => array('supports_connection_test'=>false,'supports_field_discovery'=>false,'provider_type'=>'commercial_api','unsupported_message'=>'Supporto non ancora disponibile in questa versione.','label'=>'SafetyWing','provider_key'=>'safetywing','description'=>'Referral e Remote Health API.','modes'=>array('referral_link','api'),'settings_fields'=>array('product_line','environment','base_url','mode','tracking_subid'),'credentials_fields'=>array('api_key','referral_url','partner_id'),'required_fields'=>array('product_line','mode'),'optional_fields'=>array('api_key','referral_url','partner_id'),'help_text'=>'Remote Health API usa X-API-KEY; Ambassador usa referral link.','commercial_notes'=>''),
        );
    }
    private static function common_settings(){ return array('environment','base_url','language','locale','currency','market','campaign','integration_mode','endpoint_path','user_agent','api_version'); }
    private static function viator_settings(){ return array(
        array('key'=>'environment','label'=>'Environment','type'=>'select','default'=>'sandbox','required'=>true,'options'=>array(
            array('value'=>'sandbox','label'=>'Sandbox'),
            array('value'=>'production','label'=>'Production'),
        )),
        array('key'=>'accept_language','label'=>'Accept-Language','type'=>'text','default'=>'it','required'=>true,'placeholder'=>'it','help'=>'Lingua di risposta Viator (es. it, en-US).'),
        array('key'=>'api_version','label'=>'API version','type'=>'text','default'=>'2.0','required'=>true,'placeholder'=>'2.0'),
        array('key'=>'currency','label'=>'Currency','type'=>'text','default'=>'EUR','placeholder'=>'EUR'),
        array('key'=>'search_model','label'=>'Search model','type'=>'select','default'=>'products_search','required'=>true,'options'=>array(
            array('value'=>'products_search','label'=>'Products Search (/products/search)'),
            array('value'=>'freetext_search','label'=>'Freetext Search (/search/freetext)'),
        )),
        array('key'=>'default_destination_id','label'=>'Default destination ID (Viator)','type'=>'text','placeholder'=>'es. d57','help'=>'ID destinazione Viator usato da /products/search. Non è un termine WordPress.'),
        array('key'=>'default_search_term','label'=>'Default search term','type'=>'text','placeholder'=>'es. Colosseo Roma','help'=>'Termine usato da /search/freetext.'),
        array('key'=>'result_count','label'=>'Result count','type'=>'number','default'=>'5','placeholder'=>'5'),
        array('key'=>'sort','label'=>'Sort','type'=>'text','default'=>'DEFAULT','placeholder'=>'DEFAULT'),
        array('key'=>'sort_order','label'=>'Sort order','type'=>'select','default'=>'','options'=>array(
            array('value'=>'','label'=>'Automatico (default Viator)'),
            array('value'=>'ASCENDING','label'=>'ASCENDING'),
            array('value'=>'DESCENDING','label'=>'DESCENDING'),
        ),'help'=>'Usato solo per sort che supportano ordinamento custom. Lascia vuoto per comportamento predefinito Viator.'),
        array('key'=>'campaign_value','label'=>'Campaign value','type'=>'text','placeholder'=>'opzionale'),
        array('key'=>'target_lander','label'=>'Target lander','type'=>'text','default'=>'','placeholder'=>'opzionale','help'=>'Parametro opzionale. Lascia vuoto per usare la landing affiliate ottimizzata da Viator.'),
        array('key'=>'partner_access_level','label'=>'Partner access level','type'=>'select','default'=>'basic_affiliate','options'=>array(
            array('value'=>'basic_affiliate','label'=>'Basic Affiliate'),
            array('value'=>'full_affiliate','label'=>'Full Affiliate'),
            array('value'=>'full_affiliate_booking','label'=>'Full Affiliate Booking'),
            array('value'=>'merchant','label'=>'Merchant'),
        ),'help'=>'Informativo: non è una credenziale.'),
    ); }

    private static function viator_credentials(){ return array(
        array('key'=>'api_key','label'=>'Viator API key','type'=>'password','required'=>true,'placeholder'=>'già salvato','help'=>'Credenziale segreta inviata come header exp-api-key. Non verrà mai mostrata in chiaro.'),
    ); }

    private static function common_credentials(){ return array('api_key','access_token','bearer_token','affiliate_id','site_id','client_id','client_secret','username','password','partner_id','referral_url','tracking_code','xml_api_key'); }
}
